# ─── LangGraph Planner-Executor Agent ──────────────────────────────────────────
# Converted from LangChain Plan-Execute pattern to LangGraph
# Graph flow: START → planner_node → executor_node → (loop until done) → END

import json
import re
from typing import TypedDict, List, Dict, Any

from langgraph.graph import StateGraph, START, END
from langchain_core.messages import HumanMessage, SystemMessage


# ═══════════════════════════════════════════════════════════════════════════════
# 1. STATE DEFINITION
# ═══════════════════════════════════════════════════════════════════════════════

class AgentState(TypedDict):
    goal: str                          # User input / objective
    plan: List[Dict[str, Any]]         # List of steps generated by planner
    current_step: int                  # Tracks which step to execute next
    results: List[Dict[str, Any]]      # Outputs from executed steps


# ─── Planner System Prompt ─────────────────────────────────────────────────────

PLAN_SYSTEM = """Break the user goal into an ordered JSON list of steps.
Each step MUST follow this EXACT schema:
  {"step": int, "description": str, "tool": str or null, "args": dict or null}

Available MCP tools and their EXACT argument names:
  - calculator(expression: str)                → evaluate a math expression safely
  - add(a: float, b: float)                   → add two numbers
  - subtract(a: float, b: float)              → subtract b from a
  - multiply(a: float, b: float)              → multiply two numbers
  - divide(a: float, b: float)                → divide a by b
  - search_web(query: str)                     → search the web for real-time information
  - search_news(query: str)                    → search for latest news
  - get_current_weather(city: str)             → get current weather for a city
  - get_weather_forecast(city: str, days: int) → get weather forecast for N days

Use null for tool/args on synthesis or writing steps.
Return ONLY a valid JSON array. No markdown, no explanation."""


# ─── Tool Argument Safety ─────────────────────────────────────────────────────

TOOL_ARG_MAP = {
    "calculator":           "expression",
    "search_web":           "query",
    "search_news":          "query",
    "get_current_weather":  "city",
    "get_weather_forecast": "city",
    "add":                  "a",
    "subtract":             "a",
    "multiply":             "a",
    "divide":               "a",
}


def safe_args(tool_name: str, raw_args: dict) -> dict:
    """Remap hallucinated arg names to the correct parameter."""
    expected = TOOL_ARG_MAP.get(tool_name)
    if not expected or expected in raw_args:
        return raw_args
    first_val = next(iter(raw_args.values()), tool_name)
    print(f"  [!] Remapped {raw_args} -> {{'{expected}': '{first_val}'}}")
    return {expected: str(first_val)}


def extract_text(result) -> str:
    """Normalise a tool result to a plain string.

    MCP tools return a list of content blocks like:
      [{'type': 'text', 'text': '...', 'id': '...'}]
    This function extracts the 'text' field so the LLM
    receives readable context instead of raw Python dicts.
    """
    if isinstance(result, str):
        return result
    if isinstance(result, list):
        parts = [item["text"] if isinstance(item, dict) and "text" in item else str(item)
                 for item in result]
        return "\n".join(parts)
    return str(result)


# ═══════════════════════════════════════════════════════════════════════════════
# 5. GRAPH BUILDER
# ═══════════════════════════════════════════════════════════════════════════════

def build_graph(llm, tools_map: dict):
    """
    Construct and compile the LangGraph Planner-Executor workflow.

    Args:
        llm:        LangChain chat model instance
        tools_map:  dict mapping tool names → LangChain tool objects

    Returns:
        Compiled LangGraph ready for ainvoke()
    """

    # ═══════════════════════════════════════════════════════════════════════════
    # 2. PLANNER NODE
    # ═══════════════════════════════════════════════════════════════════════════

    async def planner_node(state: AgentState) -> dict:
        """
        Takes the user goal, calls the LLM, and generates a structured plan.
        Stores the plan in the state.
        """
        goal = state["goal"]

        print(f"\n{'='*60}")
        print(f"  PLANNER NODE")
        print(f"{'='*60}")
        print(f"  Goal: {goal}\n")

        # Call LLM to generate the plan
        plan_resp = llm.invoke([
            SystemMessage(content=PLAN_SYSTEM),
            HumanMessage(content=goal),
        ])

        # Extract text safely (handles both str and list-of-dict content)
        raw_text = (
            plan_resp.content
            if isinstance(plan_resp.content, str)
            else plan_resp.content[0].get("text", "")
        )

        # Clean markdown fences and parse JSON
        clean_json = re.sub(r"```json|```", "", raw_text).strip()
        plan = json.loads(clean_json)

        print(f"  Plan ({len(plan)} steps):")
        for s in plan:
            print(f"    Step {s['step']}: {s['description']}  |  tool={s.get('tool')}")
        print()

        return {
            "plan": plan,
            "current_step": 0,
            "results": [],
        }

    # ═══════════════════════════════════════════════════════════════════════════
    # 3. EXECUTOR NODE
    # ═══════════════════════════════════════════════════════════════════════════

    async def executor_node(state: AgentState) -> dict:
        """
        Executes ONE step at a time:
          - If the step specifies a tool → call the appropriate MCP tool
          - Otherwise → use the LLM for synthesis
        Stores the result and advances current_step.
        """
        idx = state["current_step"]
        step = state["plan"][idx]
        results = list(state["results"])  # copy to avoid mutating state

        print(f"\n{'='*60}")
        print(f"  EXECUTOR NODE  —  Step {step['step']}")
        print(f"{'='*60}")
        print(f"  Description: {step['description']}")

        tool_name = step.get("tool")

        if tool_name and tool_name in tools_map:
            # ── Tool call ──────────────────────────────────────────────────
            corrected = safe_args(tool_name, step.get("args") or {})
            print(f"  Calling tool: {tool_name}({corrected})")
            result = extract_text(await tools_map[tool_name].ainvoke(corrected))
        else:
            # ── LLM synthesis (no tool required) ───────────────────────────
            print(f"  Using LLM for synthesis")
            context = "\n".join(
                f"Step {r['step']}: {r['result']}" for r in results
            )
            response = llm.invoke([
                SystemMessage(
                    content=(
                        "You are a synthesis agent. "
                        "Use ONLY the exact numbers and data from the Context below. "
                        "Do NOT recalculate, re-derive, or invent any values. "
                        "If a tool already computed a number, quote it exactly as-is."
                    )
                ),
                HumanMessage(
                    content=f"{step['description']}\n\nContext:\n{context}"
                )
            ])
            result = response.content

        print(f"  Result: {result}\n")

        results.append({
            "step": step["step"],
            "description": step["description"],
            "result": result,
        })

        return {
            "current_step": idx + 1,
            "results": results,
        }

    # ═══════════════════════════════════════════════════════════════════════════
    # 4. ROUTING — Conditional edge to loop or finish
    # ═══════════════════════════════════════════════════════════════════════════

    def should_continue(state: AgentState) -> str:
        """Return 'continue' while steps remain, 'end' when all are done."""
        if state["current_step"] >= len(state["plan"]):
            return "end"
        return "continue"

    # ═══════════════════════════════════════════════════════════════════════════
    # ASSEMBLE THE GRAPH
    # ═══════════════════════════════════════════════════════════════════════════

    workflow = StateGraph(AgentState)

    # Add nodes
    workflow.add_node("planner", planner_node)
    workflow.add_node("executor", executor_node)

    # Add edges: START → planner → executor → (loop until complete) → END
    workflow.add_edge(START, "planner")
    workflow.add_edge("planner", "executor")
    workflow.add_conditional_edges(
        "executor",
        should_continue,
        {"continue": "executor", "end": END},
    )

    return workflow.compile()
